"""
Research prompts module
"""
from .research_prompts import (
    DELEGATION_PROMPT,
    FOLLOW_UP_PROMPT,
    FEEDBACK_LOOP_PROMPT,
    COMPANY_ANALYSIS_PROMPT,
    PERSON_PROFILE_PROMPT,
    TALKING_POINTS_PROMPT,
    SYNTHESIS_PROMPT,
    MULTI_AGENT_SYNTHESIS_PROMPT,
    MARKET_ANALYSIS_PROMPT,
    COMPETITOR_ANALYSIS_PROMPT,
    format_sources_for_prompt,
)

__all__ = [
    "DELEGATION_PROMPT",
    "FOLLOW_UP_PROMPT",
    "FEEDBACK_LOOP_PROMPT",
    "COMPANY_ANALYSIS_PROMPT",
    "PERSON_PROFILE_PROMPT",
    "TALKING_POINTS_PROMPT",
    "SYNTHESIS_PROMPT",
    "MULTI_AGENT_SYNTHESIS_PROMPT",
    "MARKET_ANALYSIS_PROMPT",
    "COMPETITOR_ANALYSIS_PROMPT",
    "format_sources_for_prompt",
]
